name: Deploy to Digital Ocean
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.docker.com
          username: ${{ secrets.DOCKER_API_KEY }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - name: Build, tag, and push image to Dockerhub
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t registry.docker.com/IMAGE:$IMAGE_TAG .
          docker tag registry.docker.com/IMAGE:${{ github.sha }} registry.docker.com/IMAGE:latest
          docker push registry.docker.com/IMAGE:latest
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}}
          source: "tests/a.txt,tests/b.txt"
          target: your_server_target_folder_path

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            echo "===================Pull Image========================="
            docker pull registry.docker.com/IMAGE:latest
            cd  /home/ubuntu/IMAGEUI;
            echo "=================Updating Container ==================="
            echo "REACT_APP_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}"  > env

            docker-compose config
            docker-compose -p lFOLDER  down  > /dev/null 2>&1
            docker-compose -p lFOLDER up -d  > /dev/null 2>&1
